CREATE TABLE GENRE(
    id integer NOT NULL,
    name varchar(20),
    PRIMARY KEY(id)
);

CREATE TABLE FAVORITE_LIST(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50),
    PRIMARY KEY (id)
);


CREATE TABLE MOVIE(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title varchar(100),
    release_date date,
    rating float,
    overview varchar(500),
    genre_id integer,
    favorite_list_id integer ,
    FOREIGN KEY(genre_id) REFERENCES GENRE(id) ON DELETE CASCADE,
    FOREIGN KEY(favorite_list_id) REFERENCES FAVORITE_LIST(id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);